### ISSUE TITLE
Dark Theme 

### ISSUE THREAD

**Issue by rocktimsaikia** [RocktimSaikia/github-card#2]
Currently the default theme is Light. But it would be nice if we give option to change the theme of the cards to the users.
1. It will have an `"data-theme"` attribute which will take "dark" or "default" as value.
2. If the dark theme is chosen, the card css will change accordingly.

This issue is open for anyone who is interested. ( make sure you have a basic knowledge of working with web components)

**Comment by macedonga** [comment]
Hey!
If you want I made a dark version of your project, but it is **only** dark. So you cannot switch between light and dark. If you like it feel free to use it!
https://github.com/macedonga/github-card

**Comment by rocktimsaikia** [comment]
@macedonga I like what you did. But we need to make it available as an option not as default. I will start working on this feature after a few days. Currently I'm busy with my internship. That's why I made this issue. But keep an eye for more issues :)

**Comment by rocktimsaikia** [comment]
@macedonga There are some conventional [life cycle callbacks ](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements#Using_the_lifecycle_callbacks) in a web component that we need to follow and use. you didn't use that properly. but thanks for showing interest :)
